import type { CompatibilityIssue, CompatibilityReportRequest } from './types';

interface CompatibilityReportContext extends CompatibilityReportRequest {
  appName: string;
  appVersion: string;
  operatingSystem: string;
  repositoryUrl: string;
}

function singleLine(value: string): string {
  return value.replace(/\s+/gu, ' ').trim();
}

function issueLines(issues: CompatibilityIssue[]): string {
  return issues.map((issue) => `- **${singleLine(issue.feature)}**: ${singleLine(issue.detail)}`).join('\n');
}

export function buildCompatibilityReportUrl(context: CompatibilityReportContext): string {
  const issueNames = [...new Set(context.issues.map((issue) => singleLine(issue.feature)))];
  const title = `[Compatibility] ${issueNames.slice(0, 2).join(', ')}${issueNames.length > 2 ? ` +${issueNames.length - 2} more` : ''}`;
  const body = [
    '## Compatibility report', '',
    '> Generated by TXT Sheets. No filename or workbook contents are included.', '',
    `- App: ${singleLine(context.appName)} ${singleLine(context.appVersion)}`,
    `- OS: ${singleLine(context.operatingSystem)}`,
    `- Source format: ${singleLine(context.sourceFormat)}`, '',
    '### Detected issues', '', issueLines(context.issues), '',
    '### Optional context', '',
    'What did you expect to work, and what happened instead?',
  ].join('\n');
  const params = new URLSearchParams({ title, body });
  return `${context.repositoryUrl.replace(/\/$/u, '')}/issues/new?${params.toString()}`;
}
